apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tractor-orchestrator.fullname" . }}
  labels:
    {{- include "tractor-orchestrator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tractor-orchestrator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tractor-orchestrator.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-normalizer
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'until nc -z tractor-normalizer 5002; do echo "waiting for tractor-normalizer"; sleep 5; done']
        - name: wait-for-buffer
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'until nc -z tractor-buffer 5005; do echo "waiting for tractor-buffer"; sleep 5; done']
        - name: wait-for-model
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c', 'until nc -z tractor-model 5003; do echo "waiting for tractor-model"; sleep 5; done']
      containers:
        - name: tractor-orchestrator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          command: ["/bin/sh", "-c"]
          args: ["sleep 1 && python run_xapp.py"]
          env:
          {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
          {{- end }}
          ports:
          {{- range .Values.service }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
          {{- end }}
