apiVersion: v1
kind: Service
metadata:
  name: {{ include "tractor-orchestrator.fullname" . }}
spec:
  type: {{ .Values.serviceType | default "ClusterIP" }}
  ports:
    {{- range .Values.service }}
    - name: {{ .name }}
      port: {{ .containerPort }}
      targetPort: {{ .containerPort }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "tractor-orchestrator.selectorLabels" . | nindent 4 }}