apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xchain-model.fullname" . }}
  labels:
    {{- include "xchain-model.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "xchain-model.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "xchain-model.labels" . | nindent 8 }}
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | nindent 8 }}
      {{- end }}

      containers:
        - name: xchain-model
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          env:
           {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
          {{- end }}

          ports:
          {{- range .Values.service }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
          {{- end }}

          volumeMounts:
            - name: model
              mountPath: "{{ .Values.persistentVolume.mountPath }}"
              subPath: xgb_model.json

          resources:
{{- toYaml .Values.resources | nindent 12 }}

      volumes:
        - name: model
          persistentVolumeClaim:
            claimName: {{ .Values.persistentVolume.claimName }}
