apiVersion: v1
kind: Service
metadata:
  name: {{ include "xchain-model.fullname" . }}
  labels:
    {{- include "xchain-model.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceType | default "ClusterIP" }}
  ports:
    {{- range .Values.service }}
    - name: {{ .name }}
      port: {{ .containerPort }}
      targetPort: {{ .containerPort }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "xchain-model.selectorLabels" . | nindent 4 }}
