apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tractor-kpm-simu.fullname" . }}
  labels:
    {{- include "tractor-kpm-simu.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tractor-kpm-simu.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tractor-kpm-simu.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      containers:
        - name: tractor-kpm-simu
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          env:
          {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
          {{- end }}
          volumeMounts:
            - name: kpis-csv
              mountPath: {{ .Values.volumeMounts.kpisCsv.mountPath }}
              subPath: embb_1010123456010_metrics.csv
          resources:
{{ toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: kpis-csv
          persistentVolumeClaim:
            claimName: {{ .Values.persistentVolume.claimName }}
