apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tractor-kpm-oai.fullname" . }}
  labels:
    {{- include "tractor-kpm-oai.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tractor-kpm-oai.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tractor-kpm-oai.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: tractor-kpm-oai
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CLEAN_DIR
              value: {{ .Values.env.CLEAN_DIR }}
            - name: ORCH_HOST
              value: {{ .Values.env.ORCH_HOST }}
            - name: ORCH_PORT
              value: {{ .Values.env.ORCH_PORT | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.env.LOG_LEVEL }}
          volumeMounts:
            - name: data-volume
              mountPath: {{ .Values.persistentVolume.mountPath }}
          resources:
{{ toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: {{ .Values.persistentVolume.claimName }}
