{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: tractor-kpm-oai
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: tractor-kpm-oai
  type: {{ .Values.service.type }}
  ports:
    - name: tcp
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
{{- end }}
