apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xchain-smartgw.fullname" . }}
  labels:
    {{- include "xchain-smartgw.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "xchain-smartgw.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "xchain-smartgw.labels" . | nindent 8 }}
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | nindent 8 }}
      {{- end }}

      containers:
        - name: smartgw
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}

          env:
           {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
          {{- end }}

          volumeMounts:
            - name: model
              mountPath: "{{ .Values.persistentVolume.mountPath }}"
              subPath: smartgw.pkl

          resources:
{{ toYaml .Values.resources | nindent 12 }}

      volumes:
        - name: model
          persistentVolumeClaim:
            claimName: {{ .Values.persistentVolume.claimName }}