replicaCount: 1

image:
  repository: ddocker122/tractor-xapp-mono
  tag: dev
  pullPolicy: IfNotPresent

fullnameOverride: "tractor-mono"

serviceType: ClusterIP
service:
  - name: kpm-http
    containerPort: 4200
  - name: mono-http
    containerPort: 5000

serviceAccount:
  annotations: {}
  automount: true
  create: true
  name: ''

volumeMounts:
  model:
    mountPath: /mnt/model/model.pt
  norm:
    mountPath: /mnt/model/norm.pkl

persistentVolume:
  model:
    enabled: true
    name: tractor-model-pv
    claimName: tractor-model-pvc
    size: 1Gi
    accessMode: ReadWriteMany
    hostPath: /home/lapdk/workspace/oai-v210/tractor/src/xapp/models
    reclaimPolicy: Delete
  norm:
    enabled: true
    name: tractor-normalizer-pv
    claimName: tractor-normalizer-pvc
    size: 1Gi
    accessMode: ReadWriteMany
    hostPath: /home/lapdk/workspace/oai-v210/tractor/src/xapp/models
    reclaimPolicy: Delete

env:
  MODEL_TYPE: CNN
  NCLASS: "4"
  ALL_FEATS: "31"
  STREAM_ID: default
  MODEL_PATH: /mnt/model/model.pt
  NORM_PATH: /mnt/model/norm.pkl

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
