tractor-kpm-oai:
  enabled: true
  fullnameOverride: "tractor-kpm-oai"
  nodeSelector:
    node-role: core
  env:
    ORCH_HOST: tractor-mono

tractor-kpm-simu:
  enabled: false
  fullnameOverride: "tractor-kpm-simu"
  nodeSelector:
    node-role: core
  env:
    ORCH_HOST: tractor-mono

tractor-orchestrator:
  enabled: false
  fullnameOverride: "tractor-orchestrator"
  nodeSelector:
    node-role: core

tractor-normalizer:
  enabled: false
  fullnameOverride: "tractor-normalizer"
  nodeSelector:
    node-role: core
  persistentVolume:
    hostPath:: /home/ubuntu/binh/oai-v210/tractor/src/xapp/models

tractor-buffer:
  enabled: false
  fullnameOverride: "tractor-buffer"
  nodeSelector:
    node-role: core

tractor-model:
  enabled: false
  fullnameOverride: "tractor-model"
  nodeSelector:
    node-role: core
  persistentVolume:
    hostPath:: /home/ubuntu/binh/oai-v210/tractor/src/xapp/models

tractor-mono:
  enabled: true
  fullnameOverride: "tractor-mono"
  nodeSelector:
    node-role: core
  persistentVolume:
    model:
      hostPath: /home/lapdk/workspace/oai-v210/tractor/src/xapp/models
    norm:
      hostPath: /home/lapdk/workspace/oai-v210/tractor/src/xapp/models

xchain-smartgw:
  enabled: true
  fullnameOverride: "xchain-smartgw"
  nodeSelector:
    node-role: core
  persistentVolume:
    hostPath: /home/lapdk/workspace/oai-v210/tractor/src/smartGW