replicaCount: 1

image:
  repository: ddocker122/tractor-kpm-oai
  tag: dev
  pullPolicy: IfNotPresent

fullnameOverride: "tractor-kpm-oai"

env:
  CLEAN_DIR: /data/clean
  ORCH_HOST: tractor-orchestrator
  ORCH_PORT: "4200"
  LOG_LEVEL: INFO

serviceAccount:
  create: true
  annotations: {}
  name: "tractor-kpm-oai-sa"

service:
  enabled: true
  type: ClusterIP
  port: 4200

persistentVolume:
  enabled: true
  claimName: kpm-data-pvc   # Shared with watcher & cleaner
  mountPath: /data

# Default metrics configuration
# defaultMetrics:
#   num_ues: 0.0
#   IMSI: 0.0
#   RNTI: 0.0
#   slicing_enabled: 0.0
#   slice_id: 0.0
#   slice_prb: 0.0
#   power_multiplier: 0.0
#   scheduling_policy: 0.0
#   dl_mcs: 0.0
#   dl_n_samples: 0.0
#   dl_buffer [bytes]: 0.0
#   tx_brate downlink [Mbps]: 0.0
#   tx_pkts downlink: 0.0
#   tx_errors downlink (%): 0.0
#   dl_cqi: 0.0
#   ul_mcs: 0.0
#   ul_n_samples: 0.0
#   ul_buffer [bytes]: 0.0
#   rx_brate uplink [Mbps]: 0.0
#   rx_pkts uplink: 0.0
#   rx_errors uplink (%): 0.0
#   ul_rssi: 0.0
#   ul_sinr: 0.0
#   phr: 0.0
#   sum_requested_prbs: 0.0
#   sum_granted_prbs: 0.0
#   dl_pmi: 0.0
#   dl_ri: 0.0
#   ul_n: 0.0
#   ul_turbo_iters: 0.0

# eMBB mean value default metrics configuration
# defaultMetrics:
#   num_ues: 1.0
#   IMSI: 1010123456010.0
#   RNTI: 71.0
#   slicing_enabled: 1.0
#   slice_id: 0.0
#   slice_prb: 6.0
#   power_multiplier: 1.0
#   scheduling_policy: 0.0
#   dl_mcs: 0.06061734090909091
#   dl_n_samples: 0.35
#   dl_buffer [bytes]: 100162.9340909091
#   tx_brate downlink [Mbps]: 0.0004298222954545454
#   tx_pkts downlink: 0.10454545454545454
#   tx_errors downlink (%): 0.0
#   dl_cqi: 6.867131977272727
#   ul_mcs: 0.18639893181818182
#   ul_n_samples: 0.4340909090909091
#   ul_buffer [bytes]: 0.0
#   rx_brate uplink [Mbps]: 0.0021793454545454547
#   rx_pkts uplink: 0.12727272727272726
#   rx_errors uplink (%): 0.25548590909090907
#   ul_rssi: 0.0
#   ul_sinr: 0.34768215909090905
#   phr: 0.49318181818181817
#   sum_requested_prbs: 0.075
#   sum_granted_prbs: 273.7022727272727
#   dl_pmi: 0.0
#   dl_ri: 0.0
#   ul_n: 0.0
#   ul_turbo_iters: 0.03655502272727273


# mMTC mean value default metrics configuration
# defaultMetrics:
#   num_ues: 1.0
#   IMSI: 1010123456002.0
#   RNTI: 70.9090909090909
#   slicing_enabled: 1.0
#   slice_id: 1.0
#   slice_prb: 18.0
#   power_multiplier: 1.0
#   scheduling_policy: 1.0
#   dl_mcs: 8.02769214876033
#   dl_n_samples: 32.34710743801653
#   dl_buffer [bytes]: 267.6942148760331
#   tx_brate downlink [Mbps]: 0.14230378512396696
#   tx_pkts downlink: 9.24793388429752
#   tx_errors downlink (%): 0.0
#   dl_cqi: 8.988390165289255
#   ul_mcs: 12.780345454545456
#   ul_n_samples: 30.181818181818183
#   ul_buffer [bytes]: 1282.9586776859503
#   rx_brate uplink [Mbps]: 0.3681622809917356
#   rx_pkts uplink: 8.537190082644628
#   rx_errors uplink (%): 0.0
#   ul_rssi: 0.0
#   ul_sinr: 30.238850413223144
#   phr: 27.41322314049587
#   sum_requested_prbs: 205.83471074380165
#   sum_granted_prbs: 112.06611570247934
#   dl_pmi: 0.0
#   dl_ri: 0.0
#   ul_n: 0.0
#   ul_turbo_iters: 0.8925619834710744


# URLLC mean value default metrics configuration
defaultMetrics:
  num_ues: 1.0
  IMSI: 1010123456009.0
  RNTI: 76.0
  slicing_enabled: 1.0
  slice_id: 2.0
  slice_prb: 5.0
  power_multiplier: 1.0
  scheduling_policy: 2.0
  dl_mcs: 10.802595952802358
  dl_n_samples: 216.94926253687316
  dl_buffer [bytes]: 31.102654867256636
  tx_brate downlink [Mbps]: 0.11851447752212389
  tx_pkts downlink: 62.52271386430679
  tx_errors downlink (%): 0.0
  dl_cqi: 8.00780596460177
  ul_mcs: 2.102671392920354
  ul_n_samples: 7.910914454277286
  ul_buffer [bytes]: 0.012979351032448377
  rx_brate uplink [Mbps]: 0.02723846253687316
  rx_pkts uplink: 2.3970501474926253
  rx_errors uplink (%): 13.945756696165192
  ul_rssi: 0.0
  ul_sinr: 2.807599578171091
  phr: 7.95575221238938
  sum_requested_prbs: 156.0867256637168
  sum_granted_prbs: 174.6802359882006
  dl_pmi: 0.0
  dl_ri: 0.0
  ul_n: 0.0
  ul_turbo_iters: 1.421795244837758

metricOrder:
  - num_ues
  - IMSI
  - RNTI
  - slicing_enabled
  - slice_id
  - slice_prb
  - power_multiplier
  - scheduling_policy
  - dl_mcs
  - dl_n_samples
  - dl_buffer [bytes]
  - tx_brate downlink [Mbps]
  - tx_pkts downlink
  - tx_errors downlink (%)
  - dl_cqi
  - ul_mcs
  - ul_n_samples
  - ul_buffer [bytes]
  - rx_brate uplink [Mbps]
  - rx_pkts uplink
  - rx_errors uplink (%)
  - ul_rssi
  - ul_sinr
  - phr
  - sum_requested_prbs
  - sum_granted_prbs
  - dl_pmi
  - dl_ri
  - ul_n
  - ul_turbo_iters

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}